spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: stack
    password: admin123
    driverClassName: org.postgresql.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:mapper/**/*.xml