spring:
  datasource:
    url: jdbc:postgresql://192.168.126.132:5432/testdb
    username: stack
    password: admin123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql

logging:
  level:
    root: info

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:mapper/**/*.xml
