spring:
  datasource:
    url: jdbc:postgresql://192.168.126.132:5432/testdb
    username: stack
    password: admin123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        "[format_sql]": true
        "[highlight_sql]": true

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        type: trace

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:mapper/**/*.xml
